name: Bump package version

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: "Bump version"
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          NEW_VERSION=$(npm version ${{ github.event.inputs.bump }})
          echo "New version: $NEW_VERSION"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:master "$NEW_VERSION"
